### PR TITLE
Fix moderator note being lost on reply preview

### LINKED ISSUE #657: Previewing moderator-edited reply doesn't show moderator note
If you moderator-edit a reply, add a mod note, then preview, the mod note doesn't exist. (The whole box doesn't exist, even, so "add a mod note" is unnecessary as a step.)

### PR DESCRIPTION
**Pull request by teceler**
Fixes #657 and adds a test for preview on updating replies.

### CODE REVIEW

File: spec/controllers/replies_controller_spec.rb [hunk 1]
```diff
@@ -482,6 +482,84 @@
...
     context "preview" do
+      it "takes correct actions" do
+        user = create(:user)
+        reply_post = create(:post, user: user)
+        reply = create(:reply, post: reply_post, user: user)
+        login_as(user)
+        expect(ReplyDraft.count).to eq(0)
+
+        char = create(:character, user: user)
+        icon = create(:icon)
```
Comment (Throne3d) [inline spec/controllers/replies_controller_spec.rb]: `, user: user`

File: spec/controllers/replies_controller_spec.rb [hunk 2]
```diff
@@ -482,6 +482,84 @@
     end
 
     context "preview" do
+      it "takes correct actions" do
+        user = create(:user)
+        reply_post = create(:post, user: user)
+        reply = create(:reply, post: reply_post, user: user)
+        login_as(user)
+        expect(ReplyDraft.count).to eq(0)
```
Comment (Throne3d) [inline spec/controllers/replies_controller_spec.rb]: This should be the case after the submission, too; can you check that then?

File: spec/controllers/replies_controller_spec.rb [hunk 3]
```diff
@@ -482,6 +482,84 @@
...
+        persisted = written.reload
+        expect(persisted.user).to eq(reply_post.user)
+        expect(persisted.character).to be_nil
+        expect(persisted.icon).to be_nil
+        expect(persisted.character_alias).to be_nil
+        expect(assigns(:post)).to eq(reply_post)
+        expect(assigns(:reply)).to eq(reply)
+
+        # build_template_groups:
+        expect(controller.gon.editor_user).not_to be_nil
```
Comment (Throne3d) [inline spec/controllers/replies_controller_spec.rb]: Would be nice to check this is the right user. I assume you copied this from somewhere? I'll amend it here for now.

File: spec/controllers/replies_controller_spec.rb [hunk 4]
```diff
@@ -482,6 +482,84 @@
...
+          reply: {
+            content: newcontent,
+            audit_comment: 'note'
+          }
+        }
+
+        expect(response).to render_template(:preview)
+        expect(assigns(:written).user).to eq(reply.user)
+        expect(assigns(:written).audit_comment).to eq('note')
+        expect(assigns(:written).content).to eq(newcontent)
```
Comment (Throne3d) [inline spec/controllers/replies_controller_spec.rb]: Would be good to check `controller.gon.editor_user` and `assigns(:templates)` here, briefly, too.

**Comment by Throne3d** [comment]
@Throne3d: feature spec this sometime to make sure it works. preferably tomorrow so it can merge.

**Comment by Throne3d** [comment]
Unrelated specs have been pulled out into #686 and #687, so this now contains (almost only) the stuff relating to moderator previews.
