### PR TITLE
Don't crash if the session[:user_id] is invalid

### LINKED ISSUE #752: Don't crash if client is logged in as nonexistent user
Particularly useful on staging, where we might be deleting users and yet their clients have cookies as if they're still logged in.

See 047b02bb488d44f7ffda57e09d6885daac2796ea.

### PR DESCRIPTION
**Pull request by Marri**
Mostly useful for staging environment, if you're logged in but we reset the data. Fixes #752

### CODE REVIEW

File: app/concerns/authentication.rb [hunk 1]
```diff
@@ -15,7 +15,14 @@ def logged_in?
...
 
     def current_user
-      @current_user ||= User.find_by_id(session[:user_id]) if logged_in?
+      return unless logged_in?
+      @current_user ||= User.find_by_id(session[:user_id])
+      return @current_user if @current_user
+
+      # logout - something has gone wrong, and the user id stored in session does not exist
+      reset_session
+      cookies.delete(:user_id, domain: '.glowfic.com')
```
Comment (Throne3d) [inline app/concerns/authentication.rb]: Should we extract this log-out code into some separate method, in case we change it in the future? (It's also used over in sessions#destroy)
